### ISSUE TITLE
Not working on under windows server 2003 or windows xp

### ISSUE THREAD

**Issue by DeepSilver** [CybeSystems/OdooPortable#1]
Not working on under windows server 2003 or windows xp.
Program crash on startup.
here are some screenshots
![2015-10-21_143752](https://cloud.githubusercontent.com/assets/3600848/10630559/8af12422-7801-11e5-9cfd-1e1b7fb4497b.jpg)
![2015-10-21_143727](https://cloud.githubusercontent.com/assets/3600848/10630557/88f58a5a-7801-11e5-9b3a-382dcab28dca.jpg)
![2015-10-21_150553](https://cloud.githubusercontent.com/assets/3600848/10631099/c8129de6-7805-11e5-9a11-0ac50d110042.jpg)

Dependency Walker point out dll which are not presented in windows XP / 2003
IESHIMS.DLL - is an artefact of Vista/7
WER.DLL - is related to Windows Error Reporting unused on Windows XP
INETCOMM.DLL - Microsoft Internet Messaging API.

**Comment by CybeSystems** [comment]
Hi,

thank you for the detailed report :-)

Unfortunately it seems that PyQt5/Qt5 is no longer support Windows XP. See http://doc.qt.io/qt-5/windows-issues.html

Both Products (XP, 2003 Server) are EOL and have no longer support from Microsoft.

If you really need XP support you can compile PyQT5 with "-target xp" switch (see link above)
